site_name: DoPlayDo
site_description: 'DoPlayDo'
site_url: 'https://doplaydo.com'
docs_dir: docs/
copyright: 'Copyright &copy; 2020 DoPlayDo'
repo_name: 'doplaydo/website'
repo_url: 'https://github.com/doplaydo/website'
nav:
    - Home: index.md
theme:
  name: 'material'


