site_name: DoPlayDo
site_description: 'DoPlayDo'
site_url: 'https://doplaydo.com'
copyright: 'Copyright &copy; 2020 DoPlayDo'
pages:
  - Introduction: 'index.md'
  - 'Python':
    - python/install.md
theme:
  name: material
repo_name: doplaydo/website
repo_url: https://github.com/doplaydo/website
