site_name: DoPlayDo
site_description: 'DoPlayDo'
site_url: 'https://doplaydo.com'
copyright: 'Copyright &copy; 2020 DoPlayDo'
pages:
  - Introduction: 'index.md'
  - 'Python':
    - python/install.md
extra_css:
  - 'stylesheets/extra.css'
theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: false
  palette:
    primary: 'white'
    accent: 'green'
  logo: 'img/logo_small.svg'
  favicon: 'img/favicon.ico'
  font:
    text: 'Noto Sans'
    code: 'Ubuntu Mono'
extra:
  search:
    tokenizer: '[\s\-]+'
use_directory_urls: true
markdown_extensions:
  - admonition
  - codehilite
  - toc
  - footnotes
  - meta
